package Test;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.ie.InternetExplorerDriver;

//import Flash.FlashObjectWebDriver;

public class app1 {

	
		
		public static void main(String[] args) throws Exception {
			
		      System.setProperty("webdriver.ie.driver", "C://Users//ammanrr.CORP//Downloads//IEDriverServer.exe");
		        WebDriver driver = new InternetExplorerDriver();
		
		        driver.manage().window().maximize();
		        
		        driver.manage().deleteAllCookies();
		        
		        driver.manage().timeouts().pageLoadTimeout(40, TimeUnit.SECONDS);
				
				driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
				// Generated by Selenium IDE
				  driver.get("https://www.msci.com/end-of-day-data-search");
				  Thread.sleep(6000);
				   driver.findElement(By.xpath("//*[@class='cookie-controls']/button[1]")).click();
				   
				  driver.findElement(By.xpath("//*[@id='_accepttermsbuttonsportlet_WAR_cookiemanager_']/button[1]")).click();
				   
				  Thread.sleep(5000);
				    
				  driver.switchTo().frame(0);
				   
				  Thread.sleep(5000);
				  
				  driver.findElement(By.xpath("//*[@id='templateForm:tableResult0:tbody_element']/tr[1]/td[1]/a")).click();
				  
				  Thread.sleep(5000);
				  
				  //FlashObjectWebDriver fow = new FlashObjectWebDriver(driver, "movie_player");
				 
				  JavascriptExecutor js = (JavascriptExecutor) driver;
				  WebElement element = null;
				  element = (WebElement) js.executeScript("return document.getElementById('perfChart')");
				 element.click();
	}

}


