package Test;
/*
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.sikuli.script.FindFailed;
import org.sikuli.script.Pattern;
import org.sikuli.script.Screen;

public class DesktopAutomate {

	public static void main(String[] args) throws FindFailed, Exception {
		// TODO Auto-generated method stub

		Screen screen=new Screen();
		
		Pattern pattern=new Pattern("C:\\Users\\ammanrr.CORP\\Downloads\\sikili\\image2.jPG");
		//screen.click(pattern);
		
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\beerar\\Downloads\\Automation_2019\\chromedriver.exe");
	        WebDriver driver = new InternetExplorerDriver();
	
	        driver.manage().window().maximize();
	        
	        driver.manage().deleteAllCookies();
	        
	        driver.manage().timeouts().pageLoadTimeout(40, TimeUnit.SECONDS);
			
			driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
			// Generated by Selenium IDE
			  driver.get("https://www.msci.com/end-of-day-data-search");
			  Thread.sleep(6000);
			   driver.findElement(By.xpath("//*[@class='cookie-controls']/button[1]")).click();
			   
			 driver.findElement(By.xpath("//*[@id='_accepttermsbuttonsportlet_WAR_cookiemanager_']/button[1]")).click();
			   
			  Thread.sleep(5000);
			    
			  driver.switchTo().frame(0);
			   
			  Thread.sleep(5000);
			  
			  driver.findElement(By.xpath("//*[@id='templateForm:tableResult0:tbody_element']/tr[1]/td[1]/a")).click();
			  
			  Thread.sleep(5000);
			  screen.wait(pattern, 5000);
			  screen.click(pattern);
			  
	}

}
*/
